# GitHub Pages configuration
title: Klosh
description: Professional websites for the hospitality industry
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://klosh.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - admin/node_modules
  - admin/.gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
